// garden_zones — zone group (new file, not part of upstream ESPHome).
// Copyright (c) GardenPilot contributors.
// Licensed under the GNU General Public License v3, like ESPHome's C++ runtime; see LICENSE in this directory.
//
// A group is a set of zones served by one or more lanes (stock-style controllers generated by groups.py). Zones are
// addressed by their 0-based number inside the group; the group routes them to (lane, valve) and offers lane-aware
// queue / run / start / shutdown operations. Queuing never starts anything. The group also owns the per-zone soil
// moisture rule and answers the lanes' skip check (watchdog lockout, soil verdict); see watchdog.h and soil_skip.h.
#pragma once

#include <cstdio>
#include <optional>
#include <string>
#include <vector>

#include "esphome/components/sensor/sensor.h"
#include "esphome/core/automation.h"
#include "esphome/core/component.h"
#include "esphome/core/hal.h"
#include "esphome/core/log.h"
#include "lanes.h"
#include "soil_skip.h"
#include "sprinkler.h"
#include "watchdog.h"

namespace esphome::garden_zones {

inline constexpr const char *GROUP_TAG = "garden_zones.group";

class GardenZonesGroup : public Component {
 public:
  explicit GardenZonesGroup(std::string name) : name_(std::move(name)) {}

  void dump_config() override {
    ESP_LOGCONFIG(GROUP_TAG, "Garden zones group '%s': %zu zones, %zu lanes", this->name_.c_str(),
                  this->map_.zone_count(), this->lanes_.size());
    if (!lanes::LaneMap::valid(this->table_))
      ESP_LOGE(GROUP_TAG, "Group '%s': the zone to lane table is invalid, group actions may misroute zones",
               this->name_.c_str());
  }

  void add_lane(Sprinkler *lane) { this->lanes_.push_back(lane); }
  /// Registers the next zone (zone numbers are assigned in call order).
  void add_zone(size_t lane, size_t valve) {
    this->table_.push_back(lanes::ZoneRef{lane, valve});
    this->map_ = lanes::LaneMap(this->table_);
  }

  size_t zone_count() const { return this->map_.zone_count(); }
  size_t lane_count() const { return this->lanes_.size(); }

  void set_watchdog(GroupWatchdog *watchdog) { this->watchdog_ = watchdog; }
  bool watchdog_tripped() const { return this->watchdog_ != nullptr && this->watchdog_->tripped(); }
  void reset_watchdog() {
    if (this->watchdog_ != nullptr)
      this->watchdog_->reset();
  }

  /// Soil moisture rule of a zone (queue and cycle runs only; manual runs ignore it).
  void set_zone_soil(size_t zone, sensor::Sensor *source, float skip_above, uint32_t max_age_ms,
                     bool skip_when_unavailable) {
    if (this->soil_.size() <= zone)
      this->soil_.resize(zone + 1);
    ZoneSoil &rule = this->soil_[zone];
    rule.sensor = source;
    rule.skip_above = skip_above;
    rule.max_age_ms = max_age_ms;
    rule.when_unavailable = skip_when_unavailable ? soil::WhenUnavailable::SKIP : soil::WhenUnavailable::WATER;
    source->add_on_state_callback([this, zone](float value) {
      ZoneSoil &state = this->soil_[zone];
      state.value = value;
      state.last_update = millis();
      state.has_value = true;
    });
  }

  /// A reading older than max_age is dropped for good (until the next one arrives): 32-bit ages wrap after ~49.7 days,
  /// so a sensor that has been dead that long must not look fresh again.
  void loop() override {
    const uint32_t now = millis();
    for (ZoneSoil &rule : this->soil_) {
      if (rule.sensor != nullptr && rule.has_value && soil::age_ms(now, rule.last_update) > rule.max_age_ms)
        rule.has_value = false;
    }
  }

  /// The lanes' skip check: nullptr = run, otherwise the reason text (valid until the next call).
  const char *skip_reason(size_t lane, size_t valve) {
    auto zone = this->map_.zone_of(lane, valve);
    if (!zone.has_value())
      return nullptr;
    if (this->watchdog_ != nullptr && this->watchdog_->zone_locked(*zone)) {
      this->reason_ = "locked by the watchdog";
      return this->reason_.c_str();
    }
    if (*zone >= this->soil_.size() || this->soil_[*zone].sensor == nullptr)
      return nullptr;
    ZoneSoil &rule = this->soil_[*zone];
    const uint32_t now = millis();
    const uint32_t age = soil::age_ms(now, rule.last_update);
    switch (soil::decide(rule.has_value, rule.value, age, rule.skip_above, rule.max_age_ms, rule.when_unavailable)) {
      case soil::Verdict::RUN:
        return nullptr;
      case soil::Verdict::RUN_UNAVAILABLE:
        // at most one WARN per minute and zone (the check runs on every queue / cycle pick)
        if (!rule.warned || (now - rule.last_warn) >= SOIL_WARN_INTERVAL_MS) {
          rule.warned = true;
          rule.last_warn = now;
          ESP_LOGW(GROUP_TAG, "zone %zu: soil sensor unavailable, watering as scheduled", *zone);
        }
        return nullptr;
      case soil::Verdict::SKIP_WET:
        char text[48];
        snprintf(text, sizeof(text), "soil moisture %.1f > %.1f", rule.value, rule.skip_above);
        this->reason_ = text;
        return this->reason_.c_str();
      case soil::Verdict::SKIP_UNAVAILABLE:
        this->reason_ = "soil sensor unavailable";
        return this->reason_.c_str();
    }
    return nullptr;
  }

  /// Adds the zone to its lane's queue; never starts anything.
  void queue_zone(optional<size_t> zone, optional<uint32_t> run_duration) {
    auto ref = this->route_(zone, "queue_zone");
    if (ref.has_value())
      this->lanes_[ref->lane]->queue_valve(ref->valve, run_duration);
  }

  size_t remove_queued_zone(optional<size_t> zone) {
    auto ref = this->route_(zone, "remove_queued_zone");
    return ref.has_value() ? this->lanes_[ref->lane]->remove_queued_valve(ref->valve) : 0;
  }

  bool is_zone_queued(optional<size_t> zone) {
    auto ref = this->route_(zone, "is_zone_queued");
    return ref.has_value() && this->lanes_[ref->lane]->is_valve_queued(ref->valve);
  }

  /// Queued zones of the whole group, interleaving the lanes (first entry of each lane, then the second, ...).
  std::vector<size_t> queued_zones() const {
    std::vector<std::vector<size_t>> orders;
    for (const Sprinkler *lane : this->lanes_)
      orders.push_back(lane->queued_valves());
    return lanes::round_order(orders, this->map_);
  }

  /// Manual run of one zone on its lane; other lanes are untouched.
  void run_zone(optional<size_t> zone, optional<uint32_t> run_duration) {
    auto ref = this->route_(zone, "run_zone");
    if (!ref.has_value())
      return;
    if (this->watchdog_ != nullptr && this->watchdog_->zone_locked(zone.value())) {
      ESP_LOGW(GROUP_TAG, "run_zone: group '%s' zone %zu is locked by the watchdog; reset it first", this->name_.c_str(),
               zone.value());
      return;
    }
    this->lanes_[ref->lane]->run_valve(ref->valve, run_duration);
  }

  /// Starts every lane that has something queued.
  void start_queue() {
    std::vector<size_t> sizes;
    for (const Sprinkler *lane : this->lanes_)
      sizes.push_back(lane->queued_valves().size());
    for (size_t index : lanes::lanes_to_start(sizes))
      this->lanes_[index]->start_from_queue();
  }

  void start_cycle() {
    for (Sprinkler *lane : this->lanes_)
      lane->start_full_cycle();
  }

  /// Shuts down every lane of this group (only this group).
  void shutdown() {
    for (Sprinkler *lane : this->lanes_)
      lane->shutdown();
  }

  std::vector<size_t> active_zones() const {
    std::vector<std::optional<size_t>> active;
    for (Sprinkler *lane : this->lanes_) {
      auto valve = lane->active_valve();
      if (valve.has_value())
        active.push_back(std::optional<size_t>(valve.value()));
      else
        active.push_back(std::nullopt);
    }
    return lanes::active_zones(active, this->map_);
  }

 protected:
  std::optional<lanes::ZoneRef> route_(const optional<size_t> &zone, const char *what) const {
    if (!zone.has_value())
      return std::nullopt;
    auto ref = this->map_.route(zone.value());
    if (!ref.has_value() || ref->lane >= this->lanes_.size()) {
      ESP_LOGW(GROUP_TAG, "%s: group '%s' has no zone %zu", what, this->name_.c_str(), zone.value());
      return std::nullopt;
    }
    return ref;
  }

  struct ZoneSoil {
    sensor::Sensor *sensor{nullptr};
    float skip_above{0};
    uint32_t max_age_ms{0};
    soil::WhenUnavailable when_unavailable{soil::WhenUnavailable::WATER};
    float value{0};
    uint32_t last_update{0};
    bool has_value{false};
    bool warned{false};
    uint32_t last_warn{0};
  };
  static constexpr uint32_t SOIL_WARN_INTERVAL_MS = 60000;

  std::string name_;
  GroupWatchdog *watchdog_{nullptr};
  std::vector<ZoneSoil> soil_;
  std::string reason_;
  std::vector<Sprinkler *> lanes_;
  std::vector<lanes::ZoneRef> table_;
  lanes::LaneMap map_;
};

template<typename... Ts> class QueueZoneAction final : public Action<Ts...> {
 public:
  explicit QueueZoneAction(GardenZonesGroup *group) : group_(group) {}
  TEMPLATABLE_VALUE(size_t, zone_number)
  TEMPLATABLE_VALUE(uint32_t, zone_run_duration)
  void play(const Ts &...x) override {
    this->group_->queue_zone(this->zone_number_.optional_value(x...), this->zone_run_duration_.optional_value(x...));
  }

 protected:
  GardenZonesGroup *group_;
};

template<typename... Ts> class RemoveQueuedZoneAction final : public Action<Ts...> {
 public:
  explicit RemoveQueuedZoneAction(GardenZonesGroup *group) : group_(group) {}
  TEMPLATABLE_VALUE(size_t, zone_number)
  void play(const Ts &...x) override { this->group_->remove_queued_zone(this->zone_number_.optional_value(x...)); }

 protected:
  GardenZonesGroup *group_;
};

template<typename... Ts> class RunZoneAction final : public Action<Ts...> {
 public:
  explicit RunZoneAction(GardenZonesGroup *group) : group_(group) {}
  TEMPLATABLE_VALUE(size_t, zone_number)
  TEMPLATABLE_VALUE(uint32_t, zone_run_duration)
  void play(const Ts &...x) override {
    this->group_->run_zone(this->zone_number_.optional_value(x...), this->zone_run_duration_.optional_value(x...));
  }

 protected:
  GardenZonesGroup *group_;
};

template<typename... Ts> class StartGroupQueueAction final : public Action<Ts...> {
 public:
  explicit StartGroupQueueAction(GardenZonesGroup *group) : group_(group) {}
  void play(const Ts &...x) override { this->group_->start_queue(); }

 protected:
  GardenZonesGroup *group_;
};

template<typename... Ts> class StartGroupCycleAction final : public Action<Ts...> {
 public:
  explicit StartGroupCycleAction(GardenZonesGroup *group) : group_(group) {}
  void play(const Ts &...x) override { this->group_->start_cycle(); }

 protected:
  GardenZonesGroup *group_;
};

template<typename... Ts> class ShutdownGroupAction final : public Action<Ts...> {
 public:
  explicit ShutdownGroupAction(GardenZonesGroup *group) : group_(group) {}
  void play(const Ts &...x) override { this->group_->shutdown(); }

 protected:
  GardenZonesGroup *group_;
};

template<typename... Ts> class ResetWatchdogAction final : public Action<Ts...> {
 public:
  explicit ResetWatchdogAction(GardenZonesGroup *group) : group_(group) {}
  void play(const Ts &...x) override { this->group_->reset_watchdog(); }

 protected:
  GardenZonesGroup *group_;
};

template<typename... Ts> class WatchdogTrippedCondition final : public Condition<Ts...> {
 public:
  explicit WatchdogTrippedCondition(GardenZonesGroup *group) : group_(group) {}
  bool check(const Ts &...x) override { return this->group_->watchdog_tripped(); }

 protected:
  GardenZonesGroup *group_;
};

template<typename... Ts> class IsZoneQueuedCondition final : public Condition<Ts...> {
 public:
  explicit IsZoneQueuedCondition(GardenZonesGroup *group) : group_(group) {}
  TEMPLATABLE_VALUE(size_t, zone_number)
  bool check(const Ts &...x) override { return this->group_->is_zone_queued(this->zone_number_.optional_value(x...)); }

 protected:
  GardenZonesGroup *group_;
};

}  // namespace esphome::garden_zones
